"""Data export — save historical candles, trades, and account data to CSV/Parquet.

Exports market data generated by the exchange simulator to external files
for use in backtesting, analysis, and ML training.

Supported formats:
- CSV (built-in, no extra dependencies)
- Parquet (requires pyarrow)

Usage:
    from exchange_simulator.data_export import DataExporter

    exporter = DataExporter(exchanges, market, output_dir="data/exports")
    exporter.export_candles(symbol="BTC/USDT", exchange="binance")
    exporter.export_all()
    exporter.export_summary()
"""
import csv
import logging
import os
from datetime import UTC, datetime

logger = logging.getLogger("exchange_simulator.data_export")


class DataExporter:
    """Export simulated market data to CSV and Parquet files.

    Exports:
    - Candles (OHLCV) per symbol per exchange
    - Order history per exchange
    - Account status snapshots
    - Summary statistics
    """

    def __init__(
        self,
        exchanges: dict,
        market,
        output_dir: str = "data/exports",
        format: str = "csv",
    ):
        self.exchanges = exchanges
        self.market = market
        self.output_dir = output_dir
        self.format = format
        os.makedirs(output_dir, exist_ok=True)

    def export_candles(
        self,
        symbol: str | None = None,
        exchange: str | None = None,
    ) -> str:
        """Export candle data to CSV/Parquet.

        Args:
            symbol: Specific symbol (None = all symbols)
            exchange: Specific exchange (None = all exchanges)

        Returns:
            Path to exported file
        """
        symbols = [symbol] if symbol else list(self.market.symbols)
        exchange_ids = [exchange] if exchange else list(self.exchanges.keys())

        all_candles = []
        for ex_id in exchange_ids:
            for sym in symbols:
                candles = self.market.get_history(ex_id, sym, n=100000)
                for c in candles:
                    all_candles.append({
                        "exchange": ex_id,
                        "symbol": sym,
                        "timestamp": c.timestamp,
                        "datetime": datetime.fromtimestamp(c.timestamp, tz=UTC).isoformat(),
                        "open": c.open,
                        "high": c.high,
                        "low": c.low,
                        "close": c.close,
                        "volume": c.volume,
                    })

        if not all_candles:
            logger.warning("No candles to export")
            return ""

        filename = f"candles_{datetime.now(UTC).strftime('%Y%m%d_%H%M%S')}.{self.format}"
        filepath = os.path.join(self.output_dir, filename)

        if self.format == "parquet":
            self._write_parquet(all_candles, filepath)
        else:
            self._write_csv(all_candles, filepath)

        logger.info(f"Exported {len(all_candles)} candles to {filepath}")
        return filepath

    def export_orders(self, exchange: str | None = None) -> str:
        """Export order history to CSV."""
        exchange_ids = [exchange] if exchange else list(self.exchanges.keys())

        all_orders = []
        for ex_id in exchange_ids:
            ex = self.exchanges[ex_id]
            orders = ex.get_order_history(limit=10000)
            for o in orders:
                all_orders.append({
                    "exchange": ex_id,
                    "order_id": o.id,
                    "symbol": o.symbol,
                    "side": o.side.value,
                    "order_type": o.order_type.value,
                    "quantity": o.quantity,
                    "filled_quantity": o.filled_quantity,
                    "filled_price": o.filled_price,
                    "fee": o.fee,
                    "status": o.status.value,
                    "timestamp": o.timestamp,
                    "datetime": datetime.fromtimestamp(o.timestamp, tz=UTC).isoformat(),
                })

        if not all_orders:
            logger.info("No orders to export")
            return ""

        filename = f"orders_{datetime.now(UTC).strftime('%Y%m%d_%H%M%S')}.csv"
        filepath = os.path.join(self.output_dir, filename)
        self._write_csv(all_orders, filepath)
        logger.info(f"Exported {len(all_orders)} orders to {filepath}")
        return filepath

    def export_account_status(self) -> str:
        """Export account status snapshot for all exchanges."""
        rows = []
        for ex_id, ex in self.exchanges.items():
            status = ex.get_account_status()
            rows.append({
                "exchange": ex_id,
                "balance": status["balance"],
                "equity": status["equity"],
                "total_pnl": status["total_pnl"],
                "total_fees": status["total_fees"],
                "total_trades": status["total_trades"],
                "win_rate": status["win_rate"],
                "open_positions": len(status["positions"]),
                "exported_at": datetime.now(UTC).isoformat(),
            })

        filename = f"accounts_{datetime.now(UTC).strftime('%Y%m%d_%H%M%S')}.csv"
        filepath = os.path.join(self.output_dir, filename)
        self._write_csv(rows, filepath)
        logger.info(f"Exported account status for {len(rows)} exchanges to {filepath}")
        return filepath

    def export_positions(self) -> str:
        """Export current open positions across all exchanges."""
        rows = []
        for ex_id, ex in self.exchanges.items():
            status = ex.get_account_status()
            for p in status["positions"]:
                rows.append({
                    "exchange": ex_id,
                    "symbol": p["symbol"],
                    "side": p["side"],
                    "quantity": p["quantity"],
                    "entry_price": p["entry_price"],
                    "stop_loss": p["stop_loss"],
                    "take_profit": p["take_profit"],
                    "unrealized_pnl": p["unrealized_pnl"],
                    "opened_at": p.get("opened_at", ""),
                    "exported_at": datetime.now(UTC).isoformat(),
                })

        if rows:
            filename = f"positions_{datetime.now(UTC).strftime('%Y%m%d_%H%M%S')}.csv"
            filepath = os.path.join(self.output_dir, filename)
            self._write_csv(rows, filepath)
            logger.info(f"Exported {len(rows)} positions to {filepath}")
        else:
            logger.info("No open positions to export")
            return ""
        return filepath

    def export_all(self) -> list[str]:
        """Export all available data.

        Returns:
            List of exported file paths
        """
        files = []
        files.append(self.export_candles())
        files.append(self.export_orders())
        files.append(self.export_account_status())
        files.append(self.export_positions())
        files = [f for f in files if f]
        logger.info(f"Export complete: {len(files)} files in {self.output_dir}")
        return files

    def export_summary(self) -> str:
        """Export a summary statistics file."""
        summary = {
            "export_time": datetime.now(UTC).isoformat(),
            "exchanges": len(self.exchanges),
            "symbols": len(self.market.symbols),
            "total_candles": 0,
            "total_orders": 0,
            "total_trades": 0,
        }

        for ex_id, ex in self.exchanges.items():
            status = ex.get_account_status()
            summary["total_trades"] += status["total_trades"]
            for sym in self.market.symbols:
                candles = self.market.get_history(ex_id, sym, n=100000)
                summary["total_candles"] += len(candles)
            summary["total_orders"] += len(ex.get_order_history(limit=10000))

        filename = f"summary_{datetime.now(UTC).strftime('%Y%m%d_%H%M%S')}.csv"
        filepath = os.path.join(self.output_dir, filename)
        self._write_csv([summary], filepath)
        logger.info(f"Summary exported to {filepath}")
        return filepath

    def _write_csv(self, rows: list[dict], filepath: str) -> None:
        """Write rows to CSV file."""
        if not rows:
            return
        with open(filepath, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=rows[0].keys())
            writer.writeheader()
            writer.writerows(rows)

    def _write_parquet(self, rows: list[dict], filepath: str) -> None:
        """Write rows to Parquet file."""
        try:
            import pyarrow as pa
            import pyarrow.parquet as pq
        except ImportError:
            logger.warning("pyarrow not installed, falling back to CSV")
            filepath = filepath.replace(".parquet", ".csv")
            self._write_csv(rows, filepath)
            return

        table = pa.Table.from_pylist(rows)
        pq.write_table(table, filepath)
