from src.research.affine_arithmetic import (
    Affine,
    AffineResult,
    affine_analysis,
    affine_signal,
    robust_option_price,
    robust_portfolio_value,
)
from src.research.almgren_chriss import (
    AlmgrenChrissResult,
    almgren_chriss,
    almgren_chriss_analysis,
    efficient_frontier,
    estimate_volatility,
)
from src.research.ccm import (
    EDMResult,
    ccm,
    edm_analysis,
    edm_ccm_analysis,
    edm_signal,
    embed,
    false_nearest_neighbors,
    mutual_info,
    simplex_forecast,
)
from src.research.cramer_rao import (
    CramerRaoResult,
    compute_returns as crb_compute_returns,
    cramer_rao_analysis,
    crb_signal,
    fisher_garch,
    fisher_gaussian_mean,
    fisher_gaussian_var,
    garch_log_lik as crb_garch_log_lik,
)
from src.research.fokker_planck import (
    FokkerPlanckResult,
    compute_returns as fp_compute_returns,
    fokker_planck_analysis,
    fp_signal,
    solve_fokker_planck,
)
from src.research.free_energy import (
    FeResult,
    compute_free_energy,
    compute_returns as fe_compute_returns,
    expected_free_energy,
    fe_analysis,
    generate_policies,
    log_gaussian,
    update_beliefs,
)
from src.research.girsanov import (
    GirsanovResult,
    compute_returns as girsanov_compute_returns,
    girsanov_analysis,
    girsanov_signal,
)
from src.research.info_bottleneck import (
    IbResult,
    compute_returns as ib_compute_returns,
    ib_analysis,
    ib_signal,
    information_bottleneck,
    kl_divergence,
    quantize as ib_quantize,
)
from src.research.ito_generator import (
    ItoGeneratorResult,
    apply_generator,
    compute_returns as ito_compute_returns,
    expected_hitting_time,
    ito_generator_analysis,
    ito_signal,
    num_double_prime,
    num_prime,
)
from src.research.graph_mst import (
    GraphMSTResult,
    betweenness_centrality,
    clustering_coeff,
    correlation_matrix as graph_correlation_matrix,
    eigenvector_centrality,
    graph_mst_analysis,
    graph_signal,
    kruskal_mst,
)
from src.research.koopman import (
    KoopmanResult,
    compute_returns as koopman_compute_returns,
    dictionary,
    edmd,
    koopman_analysis,
    koopman_signal,
    power_iteration,
)
from src.research.lie_group import (
    LieResult,
    compute_returns as lie_compute_returns,
    galilean_symmetry,
    lie_algebra_coeffs,
    lie_analysis,
    lie_signal,
    scaling_symmetry,
    time_translation_symmetry,
    translation_symmetry,
)
from src.research.kolmogorov_sinai import (
    KsResult,
    block_entropy,
    compute_returns as ks_compute_returns,
    factorial,
    ks_analysis,
    ks_signal,
    largest_lyapunov,
    permutation_entropy,
    sample_entropy,
    symbolize,
)
from src.research.malliavin import (
    MalliavinResult,
    bs_call,
    bs_greeks,
    compute_returns as malliavin_compute_returns,
    malliavin_analysis,
    malliavin_greeks,
    malliavin_signal,
    norm_cdf,
    random_normal,
    simulate_paths,
)
from src.research.pontryagin import (
    PontryaginResult,
    compute_returns as pmp_compute_returns,
    pmp_signal,
    pontryagin_analysis,
    solve_pmp,
)
from src.research.renyi_entropy import (
    RenyiResult,
    compute_returns as renyi_compute_returns,
    generalized_dimensions,
    histogram,
    renyi_analysis,
    renyi_entropy,
    renyi_signal,
    tsallis_entropy,
)
from src.research.renormalization import (
    RgResult,
    autocorrelation,
    coarse_grain,
    compute_returns as rg_compute_returns,
    correlation_length,
    kurtosis_at_scale,
    rg_analysis,
    rg_signal,
    scaling_exponent,
    volatility_at_scale,
)
from src.research.rmt import (
    RMTResult,
    clean_correlation,
    jacobi_eig as rmt_jacobi_eig,
    mp_bounds,
    mp_density,
    rmt_analysis,
    rmt_signal,
)
from src.research.stochastic_control import (
    StochasticControlResult,
    compute_returns as sc_compute_returns,
    sc_signal,
    solve_hjb,
    stochastic_control_analysis,
)
from src.research.tensor_decomp import (
    TensorDecompResult,
    build_tensor,
    cp_decompose,
    tensor_decomp_analysis,
    tensor_signal,
)
from src.research.transfer_entropy import (
    TransferEntropyResult,
    quantize,
    surrogate_te,
    te_signal,
    transfer_entropy,
    transfer_entropy_analysis,
)

__all__ = [
    "AlmgrenChrissResult", "almgren_chriss", "almgren_chriss_analysis",
    "efficient_frontier", "estimate_volatility",
    "TransferEntropyResult", "transfer_entropy", "transfer_entropy_analysis",
    "surrogate_te", "quantize", "te_signal",
    "EDMResult", "edm_analysis", "edm_ccm_analysis", "edm_signal",
    "ccm", "embed", "mutual_info", "false_nearest_neighbors", "simplex_forecast",
    "CramerRaoResult", "cramer_rao_analysis", "crb_signal", "fisher_garch",
    "fisher_gaussian_mean", "fisher_gaussian_var", "crb_compute_returns", "crb_garch_log_lik",
    "KoopmanResult", "koopman_analysis", "koopman_signal", "edmd",
    "dictionary", "power_iteration", "koopman_compute_returns",
    "RMTResult", "rmt_analysis", "rmt_signal", "clean_correlation",
    "mp_bounds", "mp_density", "rmt_jacobi_eig",
    "GraphMSTResult", "graph_mst_analysis", "graph_signal", "kruskal_mst",
    "eigenvector_centrality", "betweenness_centrality", "clustering_coeff",
    "graph_correlation_matrix",
    "TensorDecompResult", "tensor_decomp_analysis", "tensor_signal",
    "build_tensor", "cp_decompose",
    "Affine", "AffineResult", "affine_analysis", "affine_signal",
    "robust_option_price", "robust_portfolio_value",
    "StochasticControlResult", "stochastic_control_analysis", "sc_signal",
    "solve_hjb", "sc_compute_returns",
    "PontryaginResult", "pontryagin_analysis", "pmp_signal", "solve_pmp",
    "pmp_compute_returns",
    "GirsanovResult", "girsanov_analysis", "girsanov_signal", "girsanov_compute_returns",
    "FokkerPlanckResult", "fokker_planck_analysis", "fp_signal", "solve_fokker_planck",
    "fp_compute_returns",
    "ItoGeneratorResult", "ito_generator_analysis", "ito_signal", "apply_generator",
    "expected_hitting_time", "num_prime", "num_double_prime", "ito_compute_returns",
    "MalliavinResult", "malliavin_analysis", "malliavin_greeks", "malliavin_signal",
    "bs_call", "bs_greeks", "norm_cdf", "random_normal", "simulate_paths",
    "malliavin_compute_returns",
    "RenyiResult", "renyi_analysis", "renyi_entropy", "renyi_signal",
    "tsallis_entropy", "generalized_dimensions", "histogram", "renyi_compute_returns",
    "KsResult", "ks_analysis", "ks_signal", "symbolize", "block_entropy",
    "permutation_entropy", "sample_entropy", "largest_lyapunov", "factorial",
    "ks_compute_returns",
    "IbResult", "ib_analysis", "ib_signal", "information_bottleneck",
    "kl_divergence", "ib_quantize", "ib_compute_returns",
    "RgResult", "rg_analysis", "rg_signal", "coarse_grain", "volatility_at_scale",
    "kurtosis_at_scale", "autocorrelation", "scaling_exponent", "correlation_length",
    "rg_compute_returns",
    "FeResult", "fe_analysis", "compute_free_energy", "expected_free_energy",
    "update_beliefs", "log_gaussian", "generate_policies", "fe_compute_returns",
    "LieResult", "lie_analysis", "lie_signal", "translation_symmetry",
    "scaling_symmetry", "time_translation_symmetry", "galilean_symmetry",
    "lie_algebra_coeffs", "lie_compute_returns",
]
