#!/usr/bin/env python3
"""CI Status Reporter — Collects all CI results and generates a markdown report.

Can be used in any CI system (GitHub Actions, GitLab CI, Jenkins, self-hosted).

Usage:
  python scripts/ci/report.py                    # Generate report from last run
  python scripts/ci/report.py --output report.md  # Write to specific file
  python scripts/ci/report.py --json              # Output as JSON
"""
import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CI_DIR = Path(__file__).resolve().parent


def run_ci_script(script_name: str) -> dict:
    """Run a CI script and capture results."""
    script = CI_DIR / script_name
    if not script.exists():
        return {"name": script_name, "status": "skipped", "output": "Script not found"}

    try:
        result = subprocess.run(
            ["bash", str(script)],
            capture_output=True,
            text=True,
            timeout=600,
            cwd=ROOT,
        )
        return {
            "name": script_name,
            "status": "pass" if result.returncode == 0 else "fail",
            "exit_code": result.returncode,
            "output": result.stdout[-2000:] if result.stdout else "",
            "error": result.stderr[-500:] if result.stderr else "",
        }
    except subprocess.TimeoutExpired:
        return {"name": script_name, "status": "timeout", "output": "Script timed out (600s)"}
    except Exception as e:
        return {"name": script_name, "status": "error", "output": str(e)}


def generate_markdown_report(results: list[dict]) -> str:
    """Generate a markdown report from CI results."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    total = len(results)
    passed = sum(1 for r in results if r["status"] == "pass")
    failed = sum(1 for r in results if r["status"] == "fail")
    skipped = sum(1 for r in results if r["status"] in ("skipped", "timeout", "error"))

    status_emoji = "✅" if failed == 0 else "❌"
    overall = "PASSED" if failed == 0 else "FAILED"

    lines = [
        f"# CI Status Report",
        f"",
        f"**Generated:** {timestamp}",
        f"**Overall:** {status_emoji} {overall}",
        f"**Summary:** {passed} passed, {failed} failed, {skipped} skipped (of {total})",
        f"",
        f"## Check Results",
        f"",
        f"| Check | Status | Exit Code |",
        f"|-------|--------|-----------|",
    ]

    for r in results:
        status = r["status"]
        icon = {"pass": "✅", "fail": "❌", "skipped": "⚠️", "timeout": "⏱️", "error": "💥"}.get(status, "❓")
        exit_code = str(r.get("exit_code", "N/A"))
        lines.append(f"| {r['name']} | {icon} {status} | {exit_code} |")

    lines.append("")
    lines.append("## Details")
    lines.append("")

    for r in results:
        if r["status"] != "pass" and r.get("output"):
            lines.append(f"### {r['name']}")
            lines.append(f"```")
            lines.append(r["output"][-1000:])
            lines.append(f"```")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by scripts/ci/report.py*")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="CI Status Reporter")
    parser.add_argument("--output", "-o", default=None, help="Output file path")
    parser.add_argument("--json", action="store_true", help="Output as JSON instead of markdown")
    parser.add_argument("--skip-build", action="store_true", help="Skip build/scan scripts")
    args = parser.parse_args()

    scripts = ["lint.sh", "test.sh", "helm-lint.sh", "security.sh"]
    if not args.skip_build:
        scripts.extend(["build.sh", "scan-images.sh"])

    results = []
    for script in scripts:
        print(f"Running {script}...")
        result = run_ci_script(script)
        results.append(result)
        print(f"  → {result['status']}")

    if args.json:
        report = json.dumps(results, indent=2)
    else:
        report = generate_markdown_report(results)

    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
        print(f"\nReport written to {args.output}")
    else:
        print(report)

    failed = sum(1 for r in results if r["status"] == "fail")
    return 1 if failed > 0 else 0


if __name__ == "__main__":
    sys.exit(main())
