import { useMemo } from 'react'
import { useUIStore } from './useUIStore'
import { useTradingStore } from './useTradingStore'
import { useToastStore } from './useToastStore'

/**
 * Builds the context object that registry.js props builders expect,
 * but reads from Zustand stores instead of receiving props from App.jsx.
 *
 * This maintains backward compatibility with the 200+ panel entries in
 * registry.js while eliminating prop drilling from App.jsx.
 */
export function usePanelContext() {
  const {
    selectedExchange,
    selectedSymbol,
    setSelectedSymbol,
    EXCHANGES,
    SYMBOLS,
    customIndicators,
    setCustomIndicators,
  } = useUIStore()

  const {
    candles,
    prices,
    accounts,
    arbitrage,
    fills,
    auditLogs,
    lastError,
    orderbooks,
    fundingRates,
    candlesToFunding,
    newsEvent,
    weekendMode,
    replayPaused,
    tradingActive,
    optionsChain,
    exchangeConnected,
    exchangeLatency,
    exchangeReconnects,
    exchangeNextReconnectIn,
    openOrders,
    submitOrder,
    closePosition,
    cancelOrder,
    cancelAllOrders,
    exchangeConnect,
    requestOptionsChain,
    sendSpeedChange,
    sendConfigUpdate,
    toggleReplay,
    scrubReplay,
    startTrading,
    stopTrading,
    signals,
    regime,
    backtestResult,
    circuitBreaker,
    portfolioResult,
    volSurfaceResult,
    cvarResult,
    stressTestResult,
    positionSizeResult,
    hawkesResult,
    fundingArbResult,
    authState,
    signalConnected,
    signalLatency,
    signalNextReconnectIn,
    sendSignalMessage,
    signalConnect,
    chartCandles,
    currentPrice,
  } = useTradingStore()

  const { toasts, addToast, removeToast, clearAll } = useToastStore()

  // Build the exchange object that registry expects (same shape as useExchangeData hook)
  const exchange = useMemo(() => ({
    candles,
    prices,
    accounts,
    arbitrage,
    fills,
    auditLogs,
    lastError,
    orderbooks,
    fundingRates,
    candlesToFunding,
    newsEvent,
    weekendMode,
    replayPaused,
    tradingActive,
    optionsChain,
    connected: exchangeConnected,
    latency: exchangeLatency,
    reconnects: exchangeReconnects,
    nextReconnectIn: exchangeNextReconnectIn,
    openOrders,
    submitOrder,
    closePosition,
    cancelOrder,
    cancelAllOrders,
    connect: exchangeConnect,
    requestOptionsChain,
    sendSpeedChange,
    sendConfigUpdate,
    toggleReplay,
    scrubReplay,
    startTrading,
    stopTrading,
  }), [candles, prices, accounts, arbitrage, fills, auditLogs, lastError, orderbooks, fundingRates,
      candlesToFunding, newsEvent, weekendMode, replayPaused, tradingActive,
      optionsChain, exchangeConnected, exchangeLatency, exchangeReconnects,
      exchangeNextReconnectIn, openOrders, submitOrder,
      closePosition, cancelOrder, cancelAllOrders, exchangeConnect, requestOptionsChain,
      sendSpeedChange, sendConfigUpdate, toggleReplay, scrubReplay,
      startTrading, stopTrading])

  // Build the signals object that registry expects (same shape as useSignalData hook)
  const signalsObj = useMemo(() => ({
    signals,
    regime,
    backtestResult,
    circuitBreaker,
    portfolioResult,
    volSurfaceResult,
    cvarResult,
    stressTestResult,
    positionSizeResult,
    hawkesResult,
    fundingArbResult,
    authState,
    connected: signalConnected,
    latency: signalLatency,
    nextReconnectIn: signalNextReconnectIn,
    sendSignalMessage,
    connect: signalConnect,
  }), [signals, regime, backtestResult, circuitBreaker, portfolioResult,
      volSurfaceResult, cvarResult, stressTestResult, positionSizeResult,
      hawkesResult, fundingArbResult, authState, signalConnected,
      signalLatency, signalNextReconnectIn, sendSignalMessage, signalConnect])

  return useMemo(() => ({
    exchange,
    signals: signalsObj,
    selectedExchange,
    selectedSymbol,
    chartCandles,
    currentPrice,
    SYMBOLS,
    EXCHANGES,
    toasts,
    addToast,
    removeToast,
    clearAll,
    setSelectedSymbol,
    customIndicators,
    setCustomIndicators,
  }), [exchange, signalsObj, selectedExchange, selectedSymbol, chartCandles,
      currentPrice, SYMBOLS, EXCHANGES, toasts, addToast, removeToast, clearAll,
      setSelectedSymbol, customIndicators, setCustomIndicators])
}
